### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by shanow7** [Chr0m0s0m3s/DeadTrap#1]
hi, I've problem with installation
![image](https://user-images.githubusercontent.com/37192410/84704764-9a5e2500-af5a-11ea-97af-07735d80aff4.png)

**Comment by Chr0m0s0m3s** [comment]
can you tell me what the last line of the error says?

**Comment by Chr0m0s0m3s** [comment]
Its that you dont have the permission to run Firefox as a root user...try using the root user's session while running the setup.py

**Comment by Chr0m0s0m3s** [comment]
issue fixed try recloning and running again

**Comment by shanow7** [comment]
nothing has changed even the root installation did not help

![image](https://user-images.githubusercontent.com/37192410/84807159-1b72f600-b007-11ea-93d2-8a3e38c7c2a0.png)

**Comment by Chr0m0s0m3s** [comment]
did you try recloning and running it without sudo?

**Comment by shanow7** [comment]
yes, bu still nothing change

![image](https://user-images.githubusercontent.com/37192410/84817491-5419cc00-b015-11ea-9ff5-8f7f2e1cee16.png)

**Comment by shanow7** [comment]
other problem

![image](https://user-images.githubusercontent.com/37192410/84818150-50d31000-b016-11ea-93e8-6a53fe38b0ca.png)

**Comment by Chr0m0s0m3s** [comment]
ok it can be solved by pip3 install python-dotenv

**Comment by shanow7** [comment]
did't help

![image](https://user-images.githubusercontent.com/37192410/84818725-3e0d0b00-b017-11ea-960e-71c46f765217.png)

**Comment by Chr0m0s0m3s** [comment]
is all your pip installations added to the path?

**Comment by shanow7** [comment]
how can I do this?

**Comment by Chr0m0s0m3s** [comment]
which desktop env are you using KDE , Gnome or xfce?

**Comment by shanow7** [comment]
GNU coreutils 8.3

**Comment by Chr0m0s0m3s** [comment]
type this in ur terminal
```
export PATH="$HOME/shanow/.local/bin:$PATH"

```

**Comment by shanow7** [comment]
still nothing

![image](https://user-images.githubusercontent.com/37192410/84822448-f38e8d00-b01c-11ea-83eb-9dabdc4b88af.png)

**Comment by Chr0m0s0m3s** [comment]
try this 
```
export PATH="$HOME/shanow/.local:$PATH"
```
then 
```
echo $PATH
```
show me the snapshot after that

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/84823061-06559180-b01e-11ea-97dd-4a9b1919b7a0.png)

**Comment by Chr0m0s0m3s** [comment]
oofe i told u to write 

```
export PATH="$HOME/shanow/.local:$PATH"
```
not 
```
export PATH="$HOME/shanow/.local/bin:$PATH"
```

that should solve the problem

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/84823696-115cf180-b01f-11ea-8584-32ad204d79c4.png)

**Comment by Chr0m0s0m3s** [comment]
you have some problems with your pip installations probably
anyways do this :
```
cd ..
sudo mv DeadTrap  /home/shanow/.local/bin
cd /home/shanow/.local/bin
ls
```
after that show me a snapshot

**Comment by shanow7** [comment]
sudo mv DeadTrap /home/shanow/.local/bin
mv: cannot use statistics on "DeadTrap": There is no such file or directory

**Comment by Chr0m0s0m3s** [comment]
bruh ffs i meant u have to use the path to DeadTrap in place of  "DeadTrap" or jus use "DeadTrap/"

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/84828382-43be1d00-b026-11ea-9aa1-bd6f776edeb4.png)

**Comment by Chr0m0s0m3s** [comment]
now take out all the files in the directory of DeadTrap to the directory in which u are currently in... and run the main.py...fixed

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/84829380-ef1ba180-b027-11ea-98f3-0598ab96f179.png)

**Comment by Chr0m0s0m3s** [comment]
oofe dude literally told u to take out all the files inside that directory...why u moved inside it?

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/84831494-b087e600-b02b-11ea-9e5e-adc617e8852a.png)

**Comment by Chr0m0s0m3s** [comment]
there is some serious mess with your setup...idk why this is happening

**Comment by Chr0m0s0m3s** [comment]
last try....type pip3 install python3-dotenv on ur terminal and ten try running see if that works

**Comment by Chr0m0s0m3s** [comment]
last try....type ```python3.8 -m pip install python-dotenv``` in ur terminal and then run main.py...hope that works

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/84856099-011c3500-b066-11ea-9ee9-5adb5e04e656.png)

**Comment by Chr0m0s0m3s** [comment]
go to the Style > banner.py > and edit the the path = '/home/chr0m0s0m3s/Style/logos' to '/logos/' should do the job.... xD

**Comment by Chr0m0s0m3s** [comment]
go to the Style > banner.py > and edit the path = '/home/chr0m0s0m3s/Style/logos' to Your path to the logos folder should do the job and another one on line 11 change that to the same path too.... xD
sorry it was my bad in the code but now fixed...hope this will get the code running for you
