### ISSUE TITLE
Hardcoded API key in main.py

### ISSUE THREAD

**Issue by stormyordos** [Chr0m0s0m3s/DeadTrap#13]
![Screenshot_20200806_145045](https://user-images.githubusercontent.com/22700501/89570623-78fc1580-d7f4-11ea-973d-d4ff29775f2c.png)

in main.py, line 23, there's an API key hardcoded directly. Suggest removing it and making it an argument.

**Comment by Chr0m0s0m3s** [comment]
Sorry back after a long break...thanks for letting me know...made sure no one notices it again...thanks alot

**Comment by stormyordos** [comment]
Still viewable in commit history though:

![image](https://user-images.githubusercontent.com/22700501/89671477-0f8e0c80-d8b1-11ea-8430-bcced7eb2c2a.png)

At this point, if you want to completely remove any trace of your API key, I suggest deleting the repository completely, and then re-creating it (ref https://stackoverflow.com/questions/13716658/how-to-delete-all-commit-history-in-github).

**Comment by Chr0m0s0m3s** [comment]
I changed the api key so no worries about it
