### ISSUE TITLE
Mysterious API

### ISSUE THREAD

**Issue by mssalvatore** [Chr0m0s0m3s/DeadTrap#14]
Can you provide more information about what this API is:
https://github.com/Chr0m0s0m3s/DeadTrap/blob/0cfbb2550bcf86c17abe6034ffad5fae7cb9c7d7/main.py#L99

It has a hard-coded API key as mentioned in issue #13 and caused a failure as mentioned in issue #11 .

What does this API do? It looks like it performs some validation and basic lookup of of details such as location, country, etc. Is the code behind this API available anywhere?

Does it collect and store any data? What is its privacy policy?

Can users host their own instance of this service or register for their own API keys?

Is this the API in question?
https://numverify.com/product

**Comment by stormyordos** [comment]
Indeed, missed it. Curious.

**Comment by Chr0m0s0m3s** [comment]
1> Client side apis cant be hidden as far as ik so to make it easier for people to use the code i made it available or else you can register your own api keys at https://numverify.com 

2> It perfoms some basic validations as you said...well i can code the entire thing of validation but would be a waste of time so used their api instead...no the code isnt opensource so as far as ik it is not available anywhere...however u can check out the phonenumbers api which performs similar functions (https://github.com/daviddrysdale/python-phonenumbers)

3> you can read the terms and conditions here (https://numverify.com/terms)

**Comment by mssalvatore** [comment]
Thanks for the information, @Chr0m0s0m3s. I'll work on a PR to add some info to the documentation, as well as make the API key configurable.
