### ISSUE TITLE
Issue :"Your monthly usage limit has been reached. Please upgrade your Subscription Plan."

### ISSUE THREAD

**Issue by laurenzm** [Chr0m0s0m3s/DeadTrap#17]
Hello,

I have the issue "Your monthly usage limit has been reached. Please upgrade your Subscription Plan.".
Wich key is it ? Can I replace it with my own ? 
How can I get a key ?

Regards,
Lau

**Comment by mssalvatore** [comment]
@laurenzm from here: https://numverify.com/product

See https://github.com/Chr0m0s0m3s/DeadTrap/issues/14 for more information.

**Comment by laurenzm** [comment]
Thanks !
