### ISSUE TITLE
issue keywork

### ISSUE THREAD

**Issue by shelu16** [Chr0m0s0m3s/DeadTrap#18]
Running Scan...Traceback (most recent call last):                                                                            
  File "main.py", line 109, in <module>                                                                                      
    browser.get(f"https://www.truecaller.com/search/{str(answer['country_code']).lower()}/{query.replace('+91', '')}")       
KeyError: 'country_code'

**Comment by mssalvatore** [comment]
This issue is a duplicate of https://github.com/Chr0m0s0m3s/DeadTrap/issues/17 and https://github.com/Chr0m0s0m3s/DeadTrap/issues/14 and https://github.com/Chr0m0s0m3s/DeadTrap/issues/13 and https://github.com/Chr0m0s0m3s/DeadTrap/issues/11.
