### ISSUE TITLE
PypI

### ISSUE THREAD

**Issue by Chr0m0s0m3s** [Chr0m0s0m3s/DeadTrap#21]
@mssalvatore thanks for all the contribution i would surely like to merge it with pypI

**Comment by mssalvatore** [comment]
The best thing to do is probably set up a github action that pushes an updated package to PyPI either 

A) Whenever there's a new commit on master
or
B) Whenever a release is tagged.

**Comment by Chr0m0s0m3s** [comment]
^:+1 aight bet

**Comment by mssalvatore** [comment]
@Chr0m0s0m3s I have a branch that makes some minor tweaks and fixes the documentation. Once the github action is set up it can be merged: https://github.com/mssalvatore/DeadTrap/tree/pypi
