### ISSUE TITLE
country code error 

### ISSUE THREAD

**Issue by pretech86** [Chr0m0s0m3s/DeadTrap#3]
thanks for the tool but when i run it and entered the phone nuber i get the following error 

Running Scan...Traceback (most recent call last):

  File "main.py", line 114, in <module>

    browser.get(f"https://www.truecaller.com/search/{str(answer['country_code']).lower()}/{query.replace('+91', '')}")

KeyError: 'country_code'

**Comment by Chr0m0s0m3s** [comment]
issue is fixed...try recloning and running again...let me know if u face any other problem
