### ISSUE TITLE
DeadTrap/Style/logo 

### ISSUE THREAD

**Issue by ddonnieddark0** [Chr0m0s0m3s/DeadTrap#6]
Hi, i need your help! I don't understand the following:

Before Running the 'main.py' file what you need to do is go to the Style folder open banner.py and replace path = DeadTrap/Style/logo with your own path to the logos folder and do the same for line 11 as well without removing {files[index]}' , 'r'

I have replaced the path to /logo with my own but it doesn't seem to be working. Do i need to create my own logo inside the logo folder? Currently the DeadTrap is in my Desktop. I tried changing the path to that folder on my Desktop but it's not working either. 

Appreciate your advice!

**Comment by Chr0m0s0m3s** [comment]
ok so where is that DeadTrap folder at in ur desktop...tell me the exact path to the DeadTrap folder

**Comment by ddonnieddark0** [comment]
the exact path to the DeadTrap folder is ~/Desktop/DeadTrap/Style/logos

**Comment by Chr0m0s0m3s** [comment]
just remove the ```banner()``` in line 90 of the main.py file then run it...would be easier for you...if that works let me know

**Comment by ddonnieddark0** [comment]
tried it, but got this error:

Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from Style.banner import banner
  File "/root/Desktop/DeadTrap/Style/banner.py", line 7
    def
      ^
SyntaxError: invalid syntax

**Comment by Chr0m0s0m3s** [comment]
Remove the line 21 then run.

**Comment by ddonnieddark0** [comment]
It's working! Thanks a lot!
