### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by shanow7** [Chr0m0s0m3s/DeadTrap#7]
Hi, I've problem with installation

/DeadTrap$ sudo python3 setup.py
[sudo] hasło użytkownika shanow: 
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
python3-pip is already the newest version (20.0.2-5kali1).
0 aktualizowanych, 0 nowo instalowanych, 0 usuwanych i 0 nieaktualizowanych.
Requirement already up-to-date: selenium in /usr/lib/python3/dist-packages (4.0.0a1)

 
 64 
 

Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/shanow/.Xauthority which is owned by shanow.)
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    version  = result[marker:].splitlines()[0]     
IndexError: list index out of range

**Comment by Chr0m0s0m3s** [comment]
why did you delete the previous issue tho? anyways run it without the ```sudo``` before python3...what the sudo does is gives u root priviledges and u r not supposed to run firefox as root

**Comment by Chr0m0s0m3s** [comment]
and after that from main.py line 90 remove banner() should work without any flaws

**Comment by shanow7** [comment]
thx is ok now :)
but when he discovered that the Facebook account is associated with this number, why doesn't he show a link or login to this account?

**Comment by Chr0m0s0m3s** [comment]
cuz facebook patched that thing somedays ago...it still works sometimes but depends on the number and the account...anyways glad that it worked

**Comment by shanow7** [comment]
it would be nice if he did something similar with the e-mail address, or if he returned the phone number or e-mail address after fb or twitter id

**Comment by shanow7** [comment]
it would be nice if he did something similar with the e-mail address, or if he returned the phone number or e-mail address after fb or twitter idTemat: Re: [Chr0m0s0m3s/DeadTrap] problem with installation (#7)Data: 2020-07-05 21:33Nadawca: "Chr0m0s0m3s" Adresat: "Chr0m0s0m3s/DeadTrap" ; DW: "jan bor" ; "Author" ; 
cuz facebook patched that thing somedays ago...it still works sometimes but depends on the number and the account...anyways glad that it worked
