### ISSUE TITLE
KEY ERROR 

### ISSUE THREAD

**Issue by manright-2018** [Chr0m0s0m3s/DeadTrap#8]
Running Scan...Traceback (most recent call last):
  File "main.py", line 110, in <module>
    browser.get(f"https://www.truecaller.com/search/{str(answer['country_code']).lower()}/{query.replace('+91', '')}")
KeyError: 'country_code'

How could i resolve the error.
plss help.
btw nice project

**Comment by Chr0m0s0m3s** [comment]
fixed...reclone and try again :))

**Comment by manright-2018** [comment]
thanks!!! for that 
but could you tell me which api did you changed and how could it fix this error.
i saw that this same error was faced a month ago too.
how could changing api key work?
and what is this api key ?

**Comment by Chr0m0s0m3s** [comment]
It changes from month to month depending on the number of times you are calling a phone number

**Comment by Z3R0C1PH3R** [comment]
This issue is happening again, I recloned and tried just now. Looks like you have reached your monthly limit again ; )

It would be better if you would have each user set up his own API key

**Comment by Chr0m0s0m3s** [comment]
Yep ig i would do that..its the better way for the work around ig...or maybe i will buy a premium one lets see
