### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by midusgrey** [Chr0m0s0m3s/DeadTrap#9]
When i run main.py the tool crashes and give me a Traceback.. tried sudo and tried it on root user.. nothing works!
![Screenshot_2020-07-17_13-41-17](https://user-images.githubusercontent.com/61030942/87782678-441f2300-c833-11ea-8cc1-3dda79b9b281.png)

**Comment by expl0it-root** [comment]
same here
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    banner()
  File "/home/expl0it/Desktop/DeadTrap/Style/banner.py", line 9, in banner
    files = os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '/DeadTrap/Style/logos/'

**Comment by expl0it-root** [comment]
just go to line 90 and remove the ```banner()``` in there.

**Comment by mssalvatore** [comment]
This issue should be resolved in https://github.com/Chr0m0s0m3s/DeadTrap/pull/12.
